### PR TITLE
Initial report for Group 7

### PR DESCRIPTION
**Pull request by sheroze1123**
Initial report can be found [here](https://github.com/sheroze1123/path/blob/master/report/report_group7.pdf).

### CODE REVIEW

**Comment by rcarson3** [comment]
Review of Group 7 from Group 4 since we couldn't find a Group 6 when we made this review

Things you did well:
- We liked that were able to use the blocking strategy in your code to help optimize your code.
- The write up was well done and showed the weak and strong scaling for the OpenMP and tuned code
- Noticing that using Canon's algorithm should help in this case

Things you could improve on:
- It looked like from your code that you currently aren't using any copy optimization techniques. You might want to look into this in order to reduce the amount of cache thrashing that could be going on.
- Your section on the MPI implementation is a little fuzzy. It is a little hard to tell what matrix you are doing the domain decomposition on as in are you doing it on L or Lnew. If you are doing it on L be careful since all the processor's will use that matrix during their calculations if you think of how the two matrices correspond to their matrix matrix multiplication counterparts.

**Comment by guptaunmukt** [comment]
Review from Team 5:

Good things:
1)  The plan to implement Canon's Algorithm to improve memory efficiency seems like a good future goal.
2)  As you mentioned in future plans, a simple loop re-ordering in your inner kernel and a change to a k-j-i order (as opposed to the base j-i-k) is a good idea. It improved the data access pattern for us, and greatly improved the performance.
3)  Report contains properly documented scaling studies for the tuned OpenMP implementations.

Remarks:
1)  The pull request did not include the mentioned "path-mpi.c" file. We could not locate the repos of the other members, and therefore could not review the relevant MPI implementation.
2)  We believe that there is gain in manual vectorization of the inner kernel. We got significant improvements over the auto-vectorized version.
3)  After doing the proposed domain decomposition through an MPI implementation, you could also incorporate the insights gained from your experiments with OpenMP in your code.
4)  Lastly, offloading to the phis is a very achievable target.

**Comment by joshbcohen** [comment]
Review from Team 6:

Strengths
- Good idea to build upon what you learned in the matmul implementation to implement Floyd-Warshall (blocking, loop ordering, etc)
- Very clear scaling studies shown for the original and tuned parallel implementations
- MPI strategy was well-explained

Things to Consider
- Some sections in your report were a bit unclear. Particularly for me, I wasn't sure if the two parallel tuned versions you talked about in your tuned scaling studies were the aforementioned blocking and loop-ordering schemes, or something different.
- Could look into other techniques from matmul, such as copy optimization, memory alignment (`_mm_malloc`, `_mm_free`), AVX instructions, etc, if you have time

**Comment by sheroze1123** [comment]
Closing pull request to open final report pull request.

**Pull request closed without merging**
